### ISSUE TITLE
README.rst contains utf-8 characters

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#14]
So this means package cannot be installed on systems which do not have current local set to utf-8. In Python 3, you get an error like:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8634: ordinal not in range(128)
```

One option would be to do `open(readme_path, encoding='utf8').read()`, but this would not work on Python 2, where you will have to use `io.open`.

Other is that you remove all unicode characters from the README.

**Comment by Stewori** [comment]
On one hand, it woud not be a big issue to get rid of the utf-chars in the readme. Most notable is the 'ö' I guess. On the other hand I thought we'd be really living in post ascii age and issues like this are so awfully 80s'ish. That's the main reason I did not realize this could be a problem before today. A bridge code for `io.open`/`open` should not be too hard to write, I'll see when I find time for this. Something like
```
try:
  open(readme_path, encoding='utf8').read()
except:
  whatever
```
would be best I suppose. Feel free to draft a PR, otherwise I'll follow up on this in some days or so.

**Comment by mitar** [comment]
Yea, but the issue is that you are supporting Python 2.7. ;-)

I think this one would be cleanest:

```python
open(readme_path, 'rb').read().decode('utf-8')
```

**Comment by mitar** [comment]
Done: #15
