### ISSUE TITLE
Tuple[(int, ...)] cannot be parsed on Python 2.7

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#16]
Having a type comment like `Tuple[(int, ...)]` cannot be parsed on Python 2.7:

```
.../pytypes/typecomment_parser.py", line 225, in _funcsigtypesfromstring
    argTp = eval(argString, globals)
  File "<string>", line 1
    (Tuple[(int, ...)])
```

**Comment by Stewori** [comment]
First note that `Tuple[(int, ...)]` is no valid Python 2.7 code and pytypes assumes that type comments contain code that is compatible with the currently running interpreter (try to process `test_type = Tuple[(int, ...)]` in ordinary Python 2.7 code). I thought this is in line with PEP 484, because they demand all imports and locals/globals (e.g. type variables) required by code in type comments. Type comments are like usual code, just in a special position.

That said, I would actually like this to work anyway. I'm thinking of some text-based preprocessing hack that allows this to work on Python 2.7. I cannot promise now that I will be able to come up with something totally reasonable. We'll see...

(So I will label this an enhancement rather than a bug...)

**Comment by mitar** [comment]
What would be an equivalent of `Tuple[(int, ...)]` in PYthon 2.7?

**Comment by Stewori** [comment]
I'm not sure. It might depend on the version of typing. From typing 3.5.3 onwards it might be
```
Tuple[(int, Ellipsis)]
```

Before that it might not be possible as a one-liner:

```
t = Tuple[(int,)]
t.__tuple_use_ellipsis__ = True
```

I did not yet find time to investigate this in more detail, so this answer is sort of preliminary. We will need some version-bridging utility method in pytypes for this. The old variant is still relevant as it's what is bundled with Python 3.5.

**Comment by Stewori** [comment]
``Tuple[int, ...]`` seems to work perfectly fine in Python 2.7. Is there a special need for ``Tuple[(int, ...)]`` rater than ``Tuple[int, ...]``?
Note that ``_issubclass_Tuple`` does not check regarding ellipsis case, but I am right now working to fix that, so ellipsis support for tuples should be available soon.
Given that ``Tuple[int, ...]`` works, I suppose we can close this issue... Thoughts?

**Comment by Stewori** [comment]
Ellipsis support was established a while ago. Given that ``Tuple[int, ...]`` syntax works fine I'll close this issue now. We can reopen if a good reason is presented. I'm also open to accept PRs that tweak the syntax parsing in typecomment_parser to support this. However, I consider it low priority at best...

**Comment by mitar** [comment]
I also do not need it anymore.
