### ISSUE TITLE
Support for non-parametrized generic types

### ISSUE THREAD

**Issue by smarie** [Stewori/pytypes#19]
```python
from typing import Dict
from pytypes import typechecked

@typechecked
def foo(a: Dict):
    pass

foo({'name': 'test2', 'surface': 1})
```

Raises 

```bash
   pytypes.exceptions.InputTypeError: 
     autoclass.tests.test_readme.foo
     called with incompatible types:
   Expected: Tuple[Dict]
   Received: Tuple[Dict[str, Union[str, int]]]
```

While it should not.
Note that it also makes PyCharm 2017.2.4 and 2017.3 crash when executed in the python terminal :

```bash
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\_pydev_bundle\pydev_console_utils.py", line 251, in add_exec
    more = self.do_add_exec(code_fragment)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevconsole.py", line 123, in do_add_exec
    command.run()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevconsole.py", line 82, in run
    self.more = self.interpreter.runsource(text, '<input>', symbol)
  File "C:\Miniconda3\envs\tools\lib\code.py", line 75, in runsource
    self.runcode(code)
  File "C:\Miniconda3\envs\tools\lib\code.py", line 95, in runcode
    self.showtraceback()
  File "C:\Miniconda3\envs\tools\lib\code.py", line 149, in showtraceback
    sys.excepthook(ei[0], ei[1], last_tb)
  File "C:\Miniconda3\envs\tools\lib\site-packages\pytypes\util.py", line 816, in _pytypes_excepthook
    traceback.print_exception(exctype, value, tb, _calc_traceback_limit(tb))
  File "C:\Miniconda3\envs\tools\lib\site-packages\pytypes\util.py", line 760, in _calc_traceback_limit
    if tb2.tb_next.tb_frame.f_code.co_filename.split(os.sep)[-2] == 'pytypes' and not \
IndexError: list index out of range
```

**Comment by Stewori** [comment]
I agree this is a bug and needs a fix.
However note that your example should actually fail in strict PEP 484 sense, because ``a: Dict`` should be treated like ``a: Dict[Any, Any]`` and the type parameters of ``Dict`` are invariant. That said, pytypes is intentionally less strict (by default) than PEP 484 because I found this behaviour too counter-intuitive. ``pytypes.covariant_mapping = False`` would cause strict PEP 484 behavior (default is ``True``).

Also note that pytypes has a flag to treat undeclared type parameters as unknown rather than ``Any``. (``pytypes.strict_unknown_check``). One can also prohibit missing type parameters at all by setting ``pytypes.check_unbound_types = False``, which lets pytypes throw an error as soon as an incompletely declared type is encountered (intended for finding holes in your one's type annotations).

**Comment by smarie** [comment]
Note that using `Dict[Any, Any]` in the above example works without any trouble (but you probably have noted it already :) )

**Comment by Stewori** [comment]
That's exactly why I admitted that this is an actual bug ;)
However, already looked into it and fixed it. Commit on the way...

**Comment by Stewori** [comment]
See https://github.com/Stewori/pytypes/commit/1752849fa55109c8c5de9f4da43883998057382f.

**Comment by Stewori** [comment]
I did not yet add a test for this. This is a remaining todo...
