### ISSUE TITLE
How to check if a type is a combination of some other types

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#42]
In one part of my code, where I am deciding how to convert a value to JSON, I do:

```
is_subclass(structural_type, typ) for typ in (str, int, float, bool)
```

What I realized is that I would be OK with all possible `Union` combinations of these as well. So if `structural_type` is `Union[str, int]` that should also pass this check. Do you have a suggestion how to do so, or a helper function which would already do this? So I wonder about complicated case like `Union[str, Union[int, bool]]` or something like that.

**Comment by Stewori** [comment]
Simply ``is_subtype(structural_type, Union[str, int, float, bool])`` should do what you want if I understand your requirement correctly (otherwise, more context would be helpful).

``Union[str, Union[int, bool]]`` is equivalent to plain ``Union[str, int, bool]`` (like ``Union[int]`` is equivalent to plain``int``) and I think pytypes handles this well (IIRC there are tests for it).

**Comment by mitar** [comment]
Oh, you are so right. Silly me. :-) Thanks!
