### ISSUE TITLE
TypeChecker does not work

### ISSUE THREAD

**Issue by agronholm** [Stewori/pytypes#50]
The following trivial script fails with ` TypeError: 'TypeChecker' object does not support indexing`:
```
from pytypes import TypeChecker

with TypeChecker():
    pass
```
Python 3.5.5.
Surely some kind of basic testing would've been nice? This works in typeguard btw.

**Comment by Stewori** [comment]
Hmm, this used to work but must have been broken somehow. You're right, proper tests would have prevented this. There are more aspects not properly tested, e.g. type logging. So far I just couldn't afford time to work this out. However, I added tests for this issue now and I think I got it fixed. Commit about to come...

Thanks for reporting it!

**Comment by agronholm** [comment]
I tried applying typeguard's version of this but, while it worked, it slowed my test suite so much that it discouraged me from using it anymore. I'm not sure what to do about it or if it's usable at all. I hope you get better results than I did.

**Comment by Stewori** [comment]
I guess the profiler approach is so slow because it is called really for *every* function. I thought about a module blacklist/whitelist approach to scope checking to relevant modules, e.g. sort out the stdlib etc. by default. Not sure if this helps. Then, pytypes is certainly slower than typeguard, e.g. because it looks for type comments and queries for stubfiles frequently. For me, typechecking was never much about performance.
That said, in pytypes there is still the option to apply a decorator to all members in a module. This should shift a lot of work to startup time compared to the profiler approach. I know you don't like that, I suppose because one cannot know what fancy magic a module might try to apply. But consider to use it only for selected modules...

**Comment by agronholm** [comment]
I'm already using whitelisting and it was still slow. I will check out that link.

**Comment by agronholm** [comment]
It looks like typo only implements a type checking decorator and not the profiler approach. It's only the profiler approach which is slow, not the other two.
