### ISSUE TITLE
Empty tuple is incompatible with Tuple[Any, ...]

### ISSUE THREAD

**Issue by jolaf** [Stewori/pytypes#69]
The following code:
```python3
from typing import Any, Tuple

from pytypes import TypeChecker

def f() -> Tuple[Any, ...]:
    return ()

with TypeChecker():
    f()
    print("OK")
```
fails as follows:
```python3
$ python3 Test.py
Traceback (most recent call last):
  File "Test.py", line 9, in <module>
    f()
  File "Test.py", line 6, in f
    return ()
pytypes.exceptions.ReturnTypeError: 
  __main__.f
  returned incompatible type:
Expected: Tuple[Any]
Received: Tuple[]
```

**Comment by Stewori** [comment]
Okay, pytypes seems to expect here a `Tuple` with at least one element. I think the convention for Tuple varargs changed some times. This will require a look how it finally turned out.

**Comment by Stewori** [comment]
Okay, this was not due to changes in typing semantics: tuple ellipsis worked the same all the time. This issue has a two-fold cause:

- When matching the tuple arags with types from a stubfile, the ellipsis property of the tuple was not preserved.

- while handled correctly in `is_subtype`, I somehow forgot tuple ellipsis handling when I wrote `is_of_type`, which accellerates type checking for certain types.

**Comment by jolaf** [comment]
Is there expected a release containing this and other fixes?

**Comment by Stewori** [comment]
See #40 (bottom). I hope to find time around eastern, no promise.
